version: '2'

services:
  jenkins:
    image: jenkins/jenkins:2.303.1-alpine
    container_name: jenkins
    ports:
      - "6850:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: